### ISSUE TITLE
Problem on Raspberry Pi 3B+ - cant run

### ISSUE THREAD

**Issue by kazz2020** [AhMyth/AhMyth-Android-RAT#142]
After npm start i got this

1 warn npm npm does not support Node.js v10.15.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, $
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
7 info using npm@5.8.0
8 info using node@v10.15.2
9 verbose run-script [ 'prestart', 'start', 'poststart' ]
10 info lifecycle @~prestart: @
11 info lifecycle @~start: @
12 verbose lifecycle @~start: unsafe-perm in lifecycle true
13 verbose lifecycle @~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/n$
14 verbose lifecycle @~start: CWD: /root/AhMyth-Android-RAT/AhMyth-Server
15 silly lifecycle @~start: Args: [ '-c', 'electron ./app' ]
16 silly lifecycle @~start: Returned: code: 1  signal: null
17 info lifecycle @~start: Failed to exec start script
18 verbose stack Error: @ start: `electron ./app`
8 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/n$
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/n$
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
19 verbose pkgid @
20 verbose cwd /root/AhMyth-Android-RAT/AhMyth-Server
21 verbose Linux 4.19.29-Re4son-v8+
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
23 verbose node v10.15.2
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error @ start: `electron ./app`
27 error Exit status 1
28 error Failed at the @ start script.
28 error This is probably not a problem with npm. There is likely additional lo$
29 verbose exit [ 1, true ]

npm install works ok but i cant run app on Pi Kali linux

**Comment by ilovelinux** [comment]
Did you install electron? What OS are you using?

**Comment by kazz2020** [comment]
Yes I have electron installed and the os is kali 2019.2... For example Kage works on my Pi
