### ISSUE TITLE
npm Start error

### ISSUE THREAD

**Issue by gituu4567** [AhMyth/AhMyth-Android-RAT#184]
root@kali:~/AhMyth-Android-RAT/AhMyth-Server# npm start

> @ start /root/AhMyth-Android-RAT/AhMyth-Server
> electron ./app

sh: 1: electron: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-30T20_58_05_522Z-debug.log
root@kali:~/AhMyth-Android-RAT/AhMyth-Server#

**Comment by LogotipX** [comment]
in folder Ahmyth-Server: npm install electron

**Comment by gituu4567** [comment]
i've tried it. and then got the error i posted above

**Comment by topperx** [comment]
> electron@1.6.11 postinstall /root/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron
> node install.js

/root/AhMyth-Android-RAT/AhMyth-Server/node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron v1.6.11 for linux-arm64 at https://github.com/electron/electron/releases/download/v1.6.11/electron-v1.6.11-linux-arm64.zip
    at Request.<anonymous> (/root/AhMyth-Android-RAT/AhMyth-Server/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:315:20)
    at Request.onRequestResponse (/root/AhMyth-Android-RAT/AhMyth-Server/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:632:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:501:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:300:12)
    at readableAddChunk (_stream_readable.js:276:9)
npm WARN AhMyth-Server No description
npm WARN AhMyth-Server No repository field.
npm WARN AhMyth-Server license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-05T03_59_24_461Z-debug.log

**Comment by HASHtechvishal** [comment]
apples-Air:react apple$ npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/apple/Desktop/react/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/apple/Desktop/react/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-05-07T12_02_10_239Z-debug.log
apples-Air:react apple$ 


how to fix it
