### ISSUE TITLE
this fails  "electron ./app"

### ISSUE THREAD

**Issue by sandmans** [AhMyth/AhMyth-Android-RAT#201]
1: electron: not found

npm ERR! Linux 5.3.0-59-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT

AhMyth-Android-RAT/AhMyth-Server/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/crypt/AhMyth-Android-RAT/AhMyth-Server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle @~start: CWD: /home/crypt/AhMyth-Android-RAT/AhMyth-Server
11 silly lifecycle @~start: Args: [ '-c', 'electron ./app' ]
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `electron ./app`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /home/crypt/AhMyth-Android-RAT/AhMyth-Server
16 error Linux 5.3.0-59-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error @ start: `electron ./app`
24 error spawn ENOENT
25 error Failed at the @ start script 'electron ./app'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the  package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron ./app
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by flleeppyy** [comment]
Install electron....

**Comment by ThonkPT** [comment]
i thought it was common sense to run npm install then npm start on a electron open source app

**Comment by zlocate** [comment]
Use `npx electron` instead (fixed at my PR)
Fixed at my PR
https://github.com/AhMyth/AhMyth-Android-RAT/pull/229
My another PR - electron updated to latest version and build-scripts work without any external dependencies
https://github.com/AhMyth/AhMyth-Android-RAT/pull/230
