### ISSUE TITLE
Camera feature / Victims connection have errors

### ISSUE THREAD

**Issue by tugdualnicolas** [AhMyth/AhMyth-Android-RAT#45]
My app will connect to the server only if i use the cloned version (Not the compiled one) (Tried on windows 10; Linux (Deepin OS)) And the device are : One plus 5, Wiko Highway 4G

And the only feature that dont work is the camera app (On the 2 devices)

**Comment by burhanuday** [comment]
Same here, here's the error from the console
`11-28 13:33:15.985 27241-28620/ahmyth.mine.king.ahmyth E/order: x0000ca
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err: java.lang.RuntimeException: takePicture failed
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at android.hardware.Camera.native_takePicture(Native Method)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at android.hardware.Camera.takePicture(Camera.java:1499)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at android.hardware.Camera.takePicture(Camera.java:1443)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at ahmyth.mine.king.ahmyth.CameraManager.startUp(CameraManager.java:34)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at ahmyth.mine.king.ahmyth.ConnectionManager.x0000ca(ConnectionManager.java:114)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at ahmyth.mine.king.ahmyth.ConnectionManager$2.call(ConnectionManager.java:57)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.emitter.Emitter.emit(Emitter.java:117)
11-28 13:33:16.149 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Socket.onevent(Socket.java:340)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Socket.onpacket(Socket.java:293)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Socket.access$100(Socket.java:19)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Socket$2$2.call(Socket.java:111)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.emitter.Emitter.emit(Emitter.java:117)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager.ondecoded(Manager.java:407)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager.access$1600(Manager.java:20)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager$7.call(Manager.java:383)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.emitter.Emitter.emit(Emitter.java:117)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.parser.Parser$Decoder.add(Parser.java:157)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager.ondata(Manager.java:399)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager.access$1000(Manager.java:20)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.client.Manager$2.call(Manager.java:350)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.emitter.Emitter.emit(Emitter.java:117)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.Socket.onPacket(Socket.java:511)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.Socket$5.call(Socket.java:313)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.emitter.Emitter.emit(Emitter.java:117)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.Transport.onData(Transport.java:126)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.engineio.client.transports.WebSocket$2$2.run(WebSocket.java:99)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at io.socket.thread.EventThread$2.run(EventThread.java:80)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-28 13:33:16.150 27241-28620/ahmyth.mine.king.ahmyth W/System.err:     at java.lang.Thread.run(Thread.java:760)`
