### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Axe-Usa** [AhMyth/AhMyth-Android-RAT#79]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/    /Escritorio/    -    -    /node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle @~start: CWD: /home/    /Escritorio/    -    -    
10 silly lifecycle @~start: Args: [ '-c', 'electron ./app' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `electron ./app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /home/    /Escritorio/    -    -    
16 verbose Linux 4.10.0-28-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `electron ./app`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

get this error?!?! why!?!?

**Comment by mo7akun** [comment]
i hat the exact same error and i solved it by this command 'sudo npm install'

**Comment by usmantanoli** [comment]
usman@kali:~$ sudo apt-get install npm 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-shell-common : Breaks: gnome-tweak-tool (< 3.21.91) but 3.14.2-2 is to be installed
 gsettings-desktop-schemas : Breaks: mutter (< 3.19.92) but 3.14.4-1~deb8u1 is to be installed
 libc6-dev : Breaks: binutils (< 2.26) but 2.25-5 is to be installed
 libdevmapper1.02.1 : Breaks: liblvm2app2.2 (< 2.02.122) but 2.02.111-2.2 is to be installed
                      Breaks: lvm2 (< 2.02.122) but 2.02.111-2.2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
